import algo

Dna = ["TCAGGATGGCAAGTTTGTCTGGCCGGTGTCCTATTGGCGAGC",
"AGAAATGGCCTCATCGGAGCGGTCACCACTGCTAGCAATCAG",
"CTTGTTTGTTCCATTACGGCAAGCGGCTAGGCACAAATCTTA",
"TCAGACCTATCCTGACAATAATTGAAATGTGCAGCAGCCAGC",
"AATGAAGAAATGAAACCCGCAAGCTGTGAGGGTTAAATGTTT",
"GCAAGCCGAACAGGGCCTCGAAACCGAGATGAATTAATGCCA",
"GCTAGCCGTAAGAAATATATCCTTCCATCATGACTGGTGGCT",
"ACGCTGCTACGTGCAAGCGGCGTATATTCCTATTATAAGGGT",
"CGGAACGCAACAATACGGGATGGGCCTGCGGCCAGCATGACG",
"GGCGTCTAATAATGGCTTGCCCTCTGATATTGGTCAGCAAGC"]
motif = algo.MedianString(Dna, 6)
print(motif)
