import algo

Dna = ["GCATAGTGATTCCTCTTTGTGAACA","ATTTTAGCTCTGTTTACCCGGTCGT","GTAGTCGCCTAGTCACGCGTCTTCG", "AGCTCGTTCTCGCACCCTCTCATTA","GTCTTCGAGACCAGGGGGGTGTGGA","GCTCATATAGAGCTAGTTCTTCCCT"]
motifs = algo.MotifEnumeration(Dna, 5,2)
for i in motifs:
    print(i)
